pw:
  ds:
    url: ${spring.datasource.mysql.url}
    driver: ${spring.datasource.mysql.driver-class-name}
    username: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
  security:
    key: BdYnxR6P31LO3QR6
    secret: mQrHjRfZ8PoQ1rYx7ZHAwUHsNrq4X8tH
    excludes: /auth/login