spring:
  # 404返回错误配置
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # json格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8