## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:com/pw/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
  global-config:
    banner: true
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      table-underline: true