server:
  port: 8080

spring:
  config:
    import:
      - classpath:config/config-basic.yml
      - classpath:config/config-pw.yml
      - classpath:config/config-mybatis.yml
      - classpath:config/config-logging.yml
  profiles:
    active: dev