spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/pwj?autoReconnect=true&useUnicode=true&charsetEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: pw
      password: pw

pw:
  # 缓存开关配置
  cache:
    open: local
  # 文件配置
  file:
    root: /data
    temp: /data/tmp